export const INIT_ASK_LIST = 'INIT_ASK_LIST'
export const LOAD_ASK_LIST = 'LOAD_ASK_LIST'
export const ADD_ASK_LIST = 'ADD_ASK_LIST'
export const INIT_QA_LIST = 'INIT_QA_LIST'
export const LOAD_QA_LIST = 'LOAD_QA_LIST'
export const ADD_QA_LIST = 'ADD_QA_LIST'
